/*
 * Copyright (C) 2013-2018 Ming Chen
 * Copyright (C) 2016-2016 Praveen Kumar Morampudi
 * Copyright (C) 2016-2016 Harshkumar Patel
 * Copyright (C) 2017-2017 Rushabh Shah
 * Copyright (C) 2013-2018 Erez Zadok
 * Copyright (c) 2013-2018 Stony Brook University
 * Copyright (c) 2013-2018 The Research Foundation for SUNY
 * This file is released under the GPL.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class secretsharing_CDCodecJNI */

#ifndef _Included_secretsharing_CDCodecJNI
#define _Included_secretsharing_CDCodecJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef secretsharing_CDCodecJNI_CRSSS
#define secretsharing_CDCodecJNI_CRSSS 0L
#undef secretsharing_CDCodecJNI_AONT_RS
#define secretsharing_CDCodecJNI_AONT_RS 1L
#undef secretsharing_CDCodecJNI_OLD_CAONT_RS
#define secretsharing_CDCodecJNI_OLD_CAONT_RS 2L
#undef secretsharing_CDCodecJNI_CAONT_RS
#define secretsharing_CDCodecJNI_CAONT_RS 3L
/*
 * Class:     secretsharing_CDCodecJNI
 * Method:    create
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_secretsharing_CDCodecJNI_create
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     secretsharing_CDCodecJNI
 * Method:    getShareSize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_secretsharing_CDCodecJNI_getShareSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     secretsharing_CDCodecJNI
 * Method:    getAlignedSecretSize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_secretsharing_CDCodecJNI_getAlignedSecretSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     secretsharing_CDCodecJNI
 * Method:    encode
 * Signature: (I[BI[B)I
 */
JNIEXPORT jint JNICALL Java_secretsharing_CDCodecJNI_encode
  (JNIEnv *, jobject, jint, jbyteArray, jint, jbyteArray);

/*
 * Class:     secretsharing_CDCodecJNI
 * Method:    decode
 * Signature: (I[BI[I[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_secretsharing_CDCodecJNI_decode
  (JNIEnv *, jobject, jint, jbyteArray, jint, jintArray, jbyteArray, jint);

/*
 * Class:     secretsharing_CDCodecJNI
 * Method:    destroy
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_secretsharing_CDCodecJNI_destroy
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
